# Generated by Django 4.2.3 on 2023-07-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
    ]
