# Generated by Django 4.2.3 on 2023-07-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_paragraph_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.paragraph'),
        ),
    ]
